/// A cached alternative-place suggestion generated by the recommendation engine.
class AlternativeSuggestion {
  final String id;
  final String originPlaceVisitId;
  final String suggestedPlaceName;
  final String suggestedOsmNodeId;
  final double suggestedLatitude;
  final double suggestedLongitude;
  final double distanceMeters;
  final double? estimatedSavings;
  final String basis; // "price" | "distance_only"
  final String category;
  final int confidenceLevel; // 0–100
  final DateTime generatedAt;
  final DateTime createdAt;

  AlternativeSuggestion({
    required this.id,
    required this.originPlaceVisitId,
    required this.suggestedPlaceName,
    required this.suggestedOsmNodeId,
    required this.suggestedLatitude,
    required this.suggestedLongitude,
    required this.distanceMeters,
    this.estimatedSavings,
    required this.basis,
    required this.category,
    this.confidenceLevel = 0,
    required this.generatedAt,
    DateTime? createdAt,
  }) : createdAt = createdAt ?? DateTime.now();

  Map<String, dynamic> toMap() => {
    'id': id,
    'origin_place_visit_id': originPlaceVisitId,
    'suggested_place_name': suggestedPlaceName,
    'suggested_osm_node_id': suggestedOsmNodeId,
    'suggested_latitude': suggestedLatitude,
    'suggested_longitude': suggestedLongitude,
    'distance_meters': distanceMeters,
    'estimated_savings': estimatedSavings,
    'basis': basis,
    'category': category,
    'confidence_level': confidenceLevel,
    'generated_at': generatedAt.toIso8601String(),
    'created_at': createdAt.toIso8601String(),
  };

  factory AlternativeSuggestion.fromMap(Map<String, dynamic> map) {
    final id = map['alternative_suggestion_id_232143'] ?? map['id'] ?? '';
    return AlternativeSuggestion(
      id: id.toString(),
      originPlaceVisitId: map['origin_place_visit_id']?.toString() ?? '',
      suggestedPlaceName: map['suggested_place_name']?.toString() ?? '',
      suggestedOsmNodeId: map['suggested_osm_node_id']?.toString() ?? '',
      suggestedLatitude: (map['suggested_latitude'] as num?)?.toDouble() ?? 0.0,
      suggestedLongitude: (map['suggested_longitude'] as num?)?.toDouble() ?? 0.0,
      distanceMeters: (map['distance_meters'] as num?)?.toDouble() ?? 0.0,
      estimatedSavings: (map['estimated_savings'] as num?)?.toDouble(),
      basis: map['basis']?.toString() ?? 'distance_only',
      category: map['category']?.toString() ?? '',
      confidenceLevel: (map['confidence_level'] as num?)?.toInt() ?? 0,
      generatedAt: _parseDate(map['generated_at']),
      createdAt: _parseDate(map['created_at']),
    );
  }

  static DateTime _parseDate(dynamic value) {
    if (value == null) return DateTime.now();
    if (value is DateTime) return value;
    return DateTime.tryParse(value.toString()) ?? DateTime.now();
  }
}
